# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RComm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bRComm.proto\x12\x05RComm\"7\n\x10\x44iscoveryRequest\x12\x11\n\tteam_name\x18\x01 \x01(\t\x12\x10\n\x08robot_id\x18\x02 \x01(\r\":\n\x11\x44iscoveryResponse\x12\x11\n\tteam_name\x18\x01 \x01(\t\x12\x12\n\nteam_color\x18\x02 \x01(\x08\"\xa2\x01\n\x08SSLSpeed\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02vx\x18\x02 \x01(\x01\x12\n\n\x02vy\x18\x03 \x01(\x01\x12\n\n\x02vw\x18\x04 \x01(\x01\x12\r\n\x05\x66ront\x18\x05 \x01(\x08\x12\x0c\n\x04\x63hip\x18\x06 \x01(\x08\x12\x0e\n\x06\x63harge\x18\x07 \x01(\x08\x12\x14\n\x0ckickStrength\x18\x08 \x01(\x01\x12\x10\n\x08\x64ribbler\x18\t \x01(\x08\x12\x11\n\tdribSpeed\x18\n \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RComm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISCOVERYREQUEST._serialized_start=22
  _DISCOVERYREQUEST._serialized_end=77
  _DISCOVERYRESPONSE._serialized_start=79
  _DISCOVERYRESPONSE._serialized_end=137
  _SSLSPEED._serialized_start=140
  _SSLSPEED._serialized_end=302
# @@protoc_insertion_point(module_scope)
